const FETCH_BUSINESSES_REQUEST = 'FETCH_BUSINESSES_REQUEST';
const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS';
const FETCH_BUSINESSES_FAILURE = 'FETCH_BUSINESSES_FAILURE';

export {
    FETCH_BUSINESSES_FAILURE,
    FETCH_BUSINESSES_REQUEST,
    FETCH_BUSINESSES_SUCCESS
};
