const BUSINESS_ACTION_TYPES = {
    FETCH_BUSINESSES_REQUEST: 'FETCH_BUSINESSES_REQUEST',
    FETCH_BUSINESSES_SUCCESS: 'FETCH_BUSINESSES_SUCCESS',
    FETCH_BUSINESSES_FAILURE: 'FETCH_BUSINESSES_FAILURE'
}

const SESSION_ACTION_TYPES = {
    FETCH_SESSION_REQUEST: 'FETCH_SESSION_REQUEST',
    FETCH_SESSION_SUCCESS: 'FETCH_SESSION_SUCCESS',
    FETCH_SESSION_FAILURE: 'FETCH_SESSION_FAILURE'
}

export {
    BUSINESS_ACTION_TYPES,
    SESSION_ACTION_TYPES
};
