const BUSINESS_ACTION_TYPES = {
    FETCH_BUSINESSES_REQUEST: 'FETCH_BUSINESSES_REQUEST',
    FETCH_BUSINESSES_SUCCESS: 'FETCH_BUSINESSES_SUCCESS',
    FETCH_BUSINESSES_FAILURE: 'FETCH_BUSINESSES_FAILURE'
}

const SESSION_ACTION_TYPES = {
    FETCH_SESSION_REQUEST: 'FETCH_SESSION_REQUEST',
    FETCH_SESSION_SUCCESS: 'FETCH_SESSION_SUCCESS',
    FETCH_SESSION_FAILURE: 'FETCH_SESSION_FAILURE'
}

const USER_ACTION_TYPES = {
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE'
}

const EMPLOYEE_ACTION_TYPES = {
    FETCH_EMPLOYEES_REQUEST: 'FETCH_EMPLOYEES_REQUEST'
}

export {
    BUSINESS_ACTION_TYPES,
    SESSION_ACTION_TYPES,
    USER_ACTION_TYPES,
    EMPLOYEE_ACTION_TYPES
};
