openapi: "3.0.0"
info:
  title: BizSoft API overview
  version: 1.0.0
paths:
  /users:
    get:
      summary: Returns all users from the system that the user has access to
      operationId: findUsers
      parameters:
        - name: pageSize
          in: query
          description: page size to return (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of users.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an user
      operationId: createUser
      tags:
        - users
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users/{userId}:
    get:
      summary: Retreive an employ with ID
      operationId: findUserById
      tags:
        - users
      parameters:
        - name: userId
components:
  schemas:
    PageInfo:
      type: object
      properties:
        number:
          type: integer
          format: int32
          minimum: 0
        total:
          type: integer
          format: int32
          minimum: 0
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        id: 1
        name: Curly Jefferson
    Users:
      type: object
      properties:
        pageInfo:
          $ref: '#/components/schemas/PageInfo'
        payload:
          items:
            $ref: '#/components/schemas/User'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    pageSizeParam:
      name: pageSize
      in: query
      description: size of page
      schema:
        type: integer
        format: int32
    pageParam:
      name: page
      in: query
      description: page number
      schema:
        type: integer
        format: int32

